#!/bin/sh
#
# Pre-commit hooks

# Add node to the path since Tower runs in a different environment
export PATH=/usr/local/bin:$PATH

# Beautify code before committing
grunt jsbeautifier

# ESLint stuff before committing
grunt eslint
