version: 2
jobs:
  build:
    working_directory: ~/mpirik/github_trello_card_events
    parallelism: 1
    shell: /bin/bash --login

    docker:
      - image: circleci/node:14

    steps:
      # Machine Setup
      - checkout

      # Dependencies
      # Restore the dependency cache
      - restore_cache:
          keys:
            # This branch if available
            - v1-dep-{{ .Branch }}-
            # Default branch if not
            - v1-dep-main-
            # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch configured correctly
            - v1-dep-
      # Delete cached node_modules folder if node version has changed
      - run:
          name: Check if node version has changed
          command: |
            node_version=$(node -v) && if [ ! -e node_modules/.node-version ] || [ $(cat node_modules/.node-version) != "$node_version" ]; then
              echo "Node version changed since last build; removing node_modules" &&
              rm -rf node_modules &&
              mkdir node_modules
            fi && echo $node_version > node_modules/.node-version
      - run:
          name: Install dependencies
          command: npm install
      # Save dependency cache
      - save_cache:
          key: v1-dep-{{ .Branch }}-{{ epoch }}
          paths:
            - ./node_modules

  deploy:
    working_directory: ~/mpirik/github_trello_card_events
    parallelism: 1
    shell: /bin/bash --login

    docker:
      - image: circleci/node:14

    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: Keyscan dokku.mpirik.com (HACK)
          command: ssh-keyscan -H dokku.mpirik.com >> ~/.ssh/known_hosts
      - run:
          name: Add git remote
          command: git remote add dokku dokku@dokku.mpirik.com:github-trello-card-events
      - run:
          name: Deploy
          command: git push -f dokku main

workflows:
  version: 2
  ci:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - build
